[debug]
# You should generate your own by "openssl rand -base64 32"
secret_key = "ETH50xrkBf0mDFdtsvgWQoe/XwrIytNoa08Qsym3h8Y="

[release]
address = "0.0.0.0"
port = 8080
keep_alive = 5
read_timeout = 5
write_timeout = 5
log_level = "critical"
secret_key = "ETH50xrkBf0mDFdtsvgWQoe/XwrIytNoa08Qsym3h8Y="
limits = { forms = 32768 }